name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        
      - name: Install dependencies
        run: uv sync
        
      - name: Build executable
        run: uv run python build.py
        
      - name: Create packages
        run: uv run python scripts/package.py all
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-packages
          path: |
            dist/*.tar.gz
            dist/*.deb
          
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        
      - name: Install dependencies
        run: uv sync
        
      - name: Build executable
        run: uv run python build.py
        
      - name: Create packages
        run: uv run python scripts/package.py all
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-packages
          path: dist/*.tar.gz
          
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        
      - name: Install dependencies
        run: uv sync
        
      - name: Build executable
        run: uv run python build.py
        
      - name: Create packages
        run: uv run python scripts/package.py all
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-packages
          path: dist/*.zip
          
  release:
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            release-artifacts/**/*.tar.gz
            release-artifacts/**/*.zip
            release-artifacts/**/*.deb
          body: |
            ## Installation
            
            ### 🚀 Quick Install (No Python Required)
            
            Download the appropriate package for your platform:
            
            **Windows:**
            - `voicebox-windows-*-installer.zip` - Installer with Start Menu integration
            - `voicebox-windows-*-portable.zip` - Portable version (no install)
            
            **macOS:**
            - `voicebox-macos-*-installer.tar.gz` - Installer with Applications integration  
            - `voicebox-macos-*-portable.tar.gz` - Portable version (no install)
            
            **Linux:**
            - `voicebox_*_amd64.deb` - Debian/Ubuntu package (recommended)
            - `voicebox-linux-*-installer.tar.gz` - Universal installer
            - `voicebox-linux-*-portable.tar.gz` - Portable version (no install)
            
            ### Usage
            
            1. Download your platform's package
            2. Extract the archive
            3. Run the installer or portable launcher
            4. Press `Ctrl+Shift+V` (or `Cmd+Shift+V` on macOS) to start recording
            
            See [README](https://github.com/${{ github.repository }}/blob/main/README.md) for configuration options.